spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jibe
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin2255
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
